### PR TITLE
Adds Testimonial Review section

### PR DESCRIPTION
**Pull request by Adebesin-Cell**
## Adds Testimonial Review section

This PR introduces the **testimonial review section** for the **Image Blender** site, showcasing user testimonials in a responsive grid layout. 

### Key Details:
1. **Responsive Grid Layout**: The testimonial grid adjusts the number of columns dynamically based on the total number of testimonials and available screen width, ensuring an optimal layout for all screen sizes.
   - The number of columns is calculated using a balance between `MAX_COLUMNS` and `ITEMS_PER_COLUMN` for a consistent visual presentation.
   - For mobile and smaller screens, the layout collapses into fewer columns to maintain readability.

2. **Theme Compatibility**: The section supports both light and dark modes, adapting text, background, and border colors to match the active theme.

3. **Next Steps**:
   - Integrate real-time testimonial data via API fetch calls.
   - Add a submission form for users to leave testimonials directly.

4. **Attached Image**: Shows the current layout and design for the testimonials section with dummy data.

This layout will serve as the foundation for future testimonial-related features like form integration and fetching data dynamically.

Macbook-Air-localhost

### CODE REVIEW

**Comment by Adebesin-Cell** [comment]
Hi @muhammadhafijur,

I noticed the `pnpm.lock` file isn't present in the current code setup. Should I add it to the commit history, or is it something we usually ignore in `.gitignore`?

Thanks for your guidance!

**Comment by muhammadhafijur** [comment]
> This PR introduces the **testimonial review section** for the **Image Blender** site, showcasing user testimonials in a responsive grid layout.

Thanks for pointing that out. I accidentally deleted it but have now added it back.

**Comment by muhammadhafijur** [comment]
Hi @Adebesin-Cell . It's showing 16 files changed. It seems like you're using a code formatter that modifies the entire codebase, making it difficult to review. I suggest you clone my repo again and make only the necessary changes. You've done a lot of work, but you can simply create a **db** folder in the root directory, add a `userReviews.json` file, and then import it into the TheTestimonial component to loop over.

Also, before creating a pull request, it's preferred to open an issue first. Make sure to pull the latest changes as well.

**Comment by Adebesin-Cell** [comment]
> > This PR introduces the **testimonial review section** for the **Image Blender** site, showcasing user testimonials in a responsive grid layout.
> 
> Thanks for pointing that out. I accidentally deleted it but have now added it back.

Thanks, that's cool! Appreciate you adding it back.

**Comment by Adebesin-Cell** [comment]
> Hi @Adebesin-Cell . It's showing 16 files changed. It seems like you're using a code formatter that modifies the entire codebase, making it difficult to review. I suggest you clone my repo again and make only the necessary changes. You've done a lot of work, but you can simply create a **db** folder in the root directory, add a `userReviews.json` file, and then import it into the TheTestimonial component to loop over.
> 
> Also, before creating a pull request, it's preferred to open an issue first. Make sure to pull the latest changes as well.

Hi @muhammadhafijur, thanks for the feedback! For the formatting, I made sure to run `pnpm format` as specified in the `package.json`. If there’s a config difference, could you let me know how I can align it with yours?

I'll go ahead and add the `userReviews.json` file as suggested. I’ll also close this PR and start fresh by opening an issue for the testimonials to follow the proper workflow.

Thanks again for the guidance!

**Pull request closed without merging**
